$OutputRoot = "$PSScriptRoot\2_Processing"

Write-Host "Stage 2 watcher started."
Write-Host "Watching: $OutputRoot"
Write-Host ""

$processed = @{}

while ($true) {

    $files = Get-ChildItem $OutputRoot -Filter "*.json" -Recurse -File

    foreach ($file in $files) {

        if ($processed.ContainsKey($file.FullName)) {
            continue
        }

        try {

            # Make sure the JSON file is no longer being written
            $before = $file.Length
            Start-Sleep -Milliseconds 500
            $after = (Get-Item $file.FullName).Length

            if ($before -ne $after) {
                continue
            }

            Write-Host "Processing: $($file.Name)"

            $json = Get-Content $file.FullName -Raw | ConvertFrom-Json

            $outputDirectory = $file.DirectoryName

            # -------------------------------------------------
            # Create participants.json
            # -------------------------------------------------

            $speakers = @(
                $json.segments |
                Where-Object { $_.speaker } |
                Select-Object -ExpandProperty speaker -Unique |
                Sort-Object
            )

            $participantsFile = Join-Path `
                $outputDirectory `
                "participants.json"

            if (-not (Test-Path $participantsFile)) {

                $participants = [ordered]@{}

                foreach ($speaker in $speakers) {
                    $participants[$speaker] = ""
                }

                $participants |
                    ConvertTo-Json |
                    Set-Content `
                        -Path $participantsFile `
                        -Encoding UTF8

                Write-Host "Created participant file: $participantsFile" `
                    -ForegroundColor Yellow
            }

            # -------------------------------------------------
            # Create Qwen transcript
            # -------------------------------------------------

            $outputFile = Join-Path `
                $outputDirectory `
                ($file.BaseName + "_for_qwen.md")

            $lines = New-Object System.Collections.Generic.List[string]

            $lines.Add("# Meeting transcript")
            $lines.Add("")
            $lines.Add("Source: $($file.Name)")
            $lines.Add("Language: $($json.language)")
            $lines.Add("")
            $lines.Add("## Participants")
            $lines.Add("")

            foreach ($speaker in $speakers) {

                $lines.Add("- $speaker")
            }

            $lines.Add("")
            $lines.Add("## Transcript")
            $lines.Add("")

            foreach ($segment in $json.segments) {

                $start = [TimeSpan]::FromSeconds($segment.start)
                $timestamp = $start.ToString("hh\:mm\:ss")

                $speaker = $segment.speaker

                if ([string]::IsNullOrWhiteSpace($speaker)) {
                    $speaker = "UNKNOWN"
                }

                $text = $segment.text.Trim()

                if (-not [string]::IsNullOrWhiteSpace($text)) {

                    $lines.Add("### [$timestamp] $speaker")
                    $lines.Add($text)
                    $lines.Add("")
                }
            }

            $lines.Add("---")
            $lines.Add("")
            $lines.Add("## Instructions for Qwen")
            $lines.Add("")
            $lines.Add("The participant names are stored in participants.json.")
            $lines.Add("")
            $lines.Add("Do not guess participant identities.")
            $lines.Add("Use only the names provided in participants.json.")
            $lines.Add("")
            $lines.Add("The transcript is automatically generated by speech recognition.")
            $lines.Add("Correct obvious transcription errors using context.")
            $lines.Add("Do not invent information.")
            $lines.Add("")

            $lines |
                Set-Content `
                    -Path $outputFile `
                    -Encoding UTF8

            $processed[$file.FullName] = $true

            Write-Host "Created: $outputFile" `
                -ForegroundColor Green

            Write-Host ""

        }
        catch {

            Write-Host "ERROR processing $($file.Name): $($_.Exception.Message)" `
                -ForegroundColor Red
        }
    }

    Start-Sleep -Seconds 3
}